# Configuration for the depth camera node - Basketball tracking

# Depth measurement parameters
depth:
  scale: 0.001           # Depth scale factor (converts raw depth to meters)
  min_depth: 0.1         # Minimum valid depth in meters
  max_depth: 8.0         # Maximum valid depth in meters
  radius: 6              # Increased radius around detection point for basketball (was 3)
  min_valid_points: 8    # Increased minimum valid points for reliable estimation (was 5)
  adaptive_radius: true  # Whether to try larger radius if not enough valid points
  max_radius: 10         # Increased maximum radius for basketball (was 7)
  calibration_file: "depth_camera_calibration.yaml"  # Path to calibration parameters
  detection_resolution:  # Resolution of detection images (YOLO/HSV)
    width: 320
    height: 320
  ball_diameter: 0.254   # Basketball diameter in meters (10 inches)
  min_height_from_ground: 0.0254  # Minimum expected height from ground (1 inch)
  max_height_from_ground: 0.254   # Max expected height from ground (10 inches - ball diameter)
  ground_tracking: true  # Enable specialized tracking for ground-based movement

# Topic configuration
topics:
  input:
    camera_info: "/ascamera/camera_publisher/depth0/camera_info"
    depth_image: "/ascamera/camera_publisher/depth0/image_raw"
    yolo_detection: "/basketball/yolo/position"
    hsv_detection: "/basketball/hsv/position"
  output:
    yolo_3d: "/basketball/yolo/position_3d"
    hsv_3d: "/basketball/hsv/position_3d"
    combined: "/basketball/detected_position"  # Combined topic

# Performance and diagnostics
diagnostics:
  log_interval: 10.0      # How often to log performance stats (seconds)
  debug_level: 0          # 0=minimal, 1=normal, 2=verbose
  threads: 1              # Number of threads for parallel processing
  error_history_size: 10  # Keep track of last 10 errors

# Common reference frame
frames:
  reference_frame: "base_link"  # Common reference frame for all sensors
  transform_timeout: 0.1        # Timeout for transform lookups in seconds
  camera_height: 0.1016         # Camera height from ground in meters (4 inches)

# Movement filtering parameters for ground-based basketball
movement:
  max_speed: 5.0          # Maximum expected basketball speed in meters/second
  position_filter_alpha: 0.7  # Position smoothing factor (higher = more responsive)
  ground_plane_tolerance: 0.03  # Tolerance for ground plane detection (3 cm)
  direction_filter_size: 5     # Number of samples for direction filtering
  acceleration_limit: 8.0      # Maximum expected acceleration in m/s²