# Configuration for the Kalman filter fusion node

startup:
  wait_for_transform: true
  transform_retry_count: 60  # Increase retry count
  transform_retry_delay: 1.0  # 1 second between retries
  required_transforms: ['camera_frame', 'lidar_frame']

# Fusion Node Configuration

topics:
  input:
    lidar: '/basketball/lidar/position'
    hsv_3d: '/basketball/hsv/position_3d'
    yolo_3d: '/basketball/yolo/position_3d'
    hsv_2d: '/basketball/hsv/position'
    yolo_2d: '/basketball/yolo/position'
    hsv_bbox: '/basketball/hsv/bbox'
    yolo_bbox: '/basketball/yolo/bbox'
  output:
    position: '/basketball/fused/position'
    velocity: '/basketball/fused/velocity'
    tracking_status: '/basketball/fused/tracking_status'
    uncertainty: '/basketball/fused/position_uncertainty'
    diagnostics: '/basketball/fusion/diagnostics'

# Process noise: how much uncertainty to add during prediction steps
process_noise:
  position: 0.1        # Position uncertainty per second squared
  velocity: 1.0        # Velocity uncertainty per second

# Measurement noise: how much to trust each sensor type
measurement_noise:
  hsv_2d: 50.0         # Pixels - high because 2D only
  yolo_2d: 30.0        # Pixels - lower because more accurate
  hsv_3d: 0.05         # Meters - from depth camera with HSV
  yolo_3d: 0.04        # Meters - from depth camera with YOLO
  lidar: 0.03          # Meters - most accurate for 3D
  hsv_2d_est3d: 0.15   # Meters - estimated 3D from 2D HSV
  yolo_2d_est3d: 0.12  # Meters - estimated 3D from 2D YOLO

# Filter tuning parameters
filter:
  max_time_diff: 0.2           # Maximum time difference for fusion (seconds)
  min_confidence_threshold: 0.5 # Minimum confidence threshold for detections
  detection_timeout: 0.5        # Time after which a detection is considered stale
  transform_timeout: 5.0        # Maximum time to wait for transform (seconds)
  transform_retry_delay: 0.5    # Delay between transform retries (seconds)
  startup_wait_time: 2.0        # Time to wait on startup before sensor processing
  ground_tracking_mode: true    # Enable ground tracking constraint
  ball_ground_height: 0.0381    # 1.5 inches in meters

# Tracking reliability thresholds
tracking:
  position_uncertainty_threshold: 0.5  # Position uncertainty threshold for reliable tracking
  velocity_uncertainty_threshold: 1.0  # Velocity uncertainty threshold for reliable tracking
  consecutive_updates_required: 3      # Required number of successful consecutive updates

# Distance-based reliability settings
reliability:
  lidar:
    close_range: 0.5            # Below this distance, LIDAR is very unreliable
    optimal_range_start: 1.0    # LIDAR becomes reliable at this distance
    optimal_range_end: 3.0      # LIDAR reliability decreases beyond this
    close_range_factor: 10.0    # Noise multiplier for close range
    optimal_range_factor: 0.6   # Noise multiplier for optimal range

# Physical measurements
physical_measurements:
  lidar_height: 0.1524      # LIDAR height from ground (6 inches)
  camera_height: 0.1016     # Camera height from ground (4 inches)
  ball_center_height: 0.0381 # Tennis ball center height from ground (1.5 inches)
  ball_radius: 0.03429      # Tennis ball radius in meters (1.35 inches)

# Advanced features
advanced_features:
  use_bbox_distance_estimation: true
  allow_tracking_with_2d_only: true
  increased_uncertainty_mode: true

# Performance optimization settings for Raspberry Pi
performance:
  enable_visualization: false  # Set to true when visualization needed
  adaptive_processing: true    # Adjust processing based on system load
  processing_priority: high    # high, normal, low
  transform_check_frequency: 3.0  # Seconds between transform checks
  skip_processing_threshold: 85  # CPU % to start skipping processing
  garbage_collection_interval: 120  # Seconds between forced GC
  process_niceness: -10  # Process priority (-20 to 19, lower is higher priority)
  selective_sensor_processing: true  # Enable dropping sensor data under load

# Diagnostics settings
diagnostics:
  history_length: 100
  debug_level: 1
